---
date: '2020-10-02T17:56:24.758Z'
docname: pyacs.gts.lib.errors
images: {}
path: /pyacs-gts-lib-errors
title: pyacs.gts.lib.errors module
---

# pyacs.gts.lib.errors module

Exception class for Gts


### exception pyacs.gts.lib.errors.GtsError()
Bases: `Exception`


### exception pyacs.gts.lib.errors.GtsInputDataNone(method_name, lib, gts)
Bases: `pyacs.gts.lib.errors.GtsError`


### exception pyacs.gts.lib.errors.GtsInputData_xyzNone(method_name, lib, gts)
Bases: `pyacs.gts.lib.errors.GtsError`


### exception pyacs.gts.lib.errors.GtsInputData_allNone(method_name, lib, gts)
Bases: `pyacs.gts.lib.errors.GtsError`


### exception pyacs.gts.lib.errors.GtsInputDataTypeError(method_name, lib, gts)
Bases: `pyacs.gts.lib.errors.GtsError`


### exception pyacs.gts.lib.errors.GtsInputDataBadDim(method_name, lib, gts)
Bases: `pyacs.gts.lib.errors.GtsError`


### exception pyacs.gts.lib.errors.GtsInputDataBadNcolumns(method_name, lib, gts)
Bases: `pyacs.gts.lib.errors.GtsError`


### exception pyacs.gts.lib.errors.GtsInputDataBadNrows(method_name, lib, gts)
Bases: `pyacs.gts.lib.errors.GtsError`


### exception pyacs.gts.lib.errors.GtsInputData_xyzTypeError(method_name, lib, gts)
Bases: `pyacs.gts.lib.errors.GtsError`


### exception pyacs.gts.lib.errors.GtsInputData_xyzBadDim(method_name, lib, gts)
Bases: `pyacs.gts.lib.errors.GtsError`


### exception pyacs.gts.lib.errors.GtsInputData_xyzBadNcolumns(method_name, lib, gts)
Bases: `pyacs.gts.lib.errors.GtsError`


### exception pyacs.gts.lib.errors.GtsInputData_xyzBadNrows(method_name, lib, gts)
Bases: `pyacs.gts.lib.errors.GtsError`


### exception pyacs.gts.lib.errors.GtsInputDataDiffShape(method_name, lib, gts)
Bases: `pyacs.gts.lib.errors.GtsError`


### exception pyacs.gts.lib.errors.GtsInputDataDiffDate(method_name, lib, gts)
Bases: `pyacs.gts.lib.errors.GtsError`


### exception pyacs.gts.lib.errors.GtsCDataError(method_name, lib, gts)
Bases: `pyacs.gts.lib.errors.GtsError`


### exception pyacs.gts.lib.errors.GtsReadFileError(method_name, lib, file_name)
Bases: `pyacs.gts.lib.errors.GtsError`
